In [1]:
import sys
sys.path.append('..')

from TransportModel import TransportModel
from Agents import StepType
import pandas as pd
import mesa

import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

file_name = 'ridesharing.csv'

In [2]:
params = {'num_drivers': range(1,6),
          'size' : 15,
          'waiting_time': None,
          'multi_pass' : True,
          'seed_int': [11,54, 111,121,127, 218, 224,341, 467, 578],
          'rate': 10,
          'total_steps': 1440,
          'strategy' : [StepType.CLOSEST, StepType.WAITING, StepType.QUEUE]}

results = mesa.batch_run(
    TransportModel,
    parameters=params,
    iterations=5,   
    max_steps=1440,
    number_processes=None,
    data_collection_period=1,
    display_progress=False,
)

In [3]:
results_df = pd.DataFrame(results)
print(results_df.keys())
results_df.to_csv(file_name, index=False)
results_df

Index(['RunId', 'iteration', 'Step', 'num_drivers', 'size', 'waiting_time',
       'multi_pass', 'seed_int', 'rate', 'total_steps', 'strategy',
       'Manhattan', 'AgentID', 'Steps', 'IdleTime', 'sec_id', 'request_time',
       'pickup_time', 'dropoff_time', 'shortest distance'],
      dtype='object')

,RunId,iteration,Step,num_drivers,size,waiting_time,multi_pass,seed_int,rate,total_steps,strategy,Manhattan,AgentID,Steps,IdleTime,sec_id,request_time,pickup_time,dropoff_time,shortest distance
0,3,0,0,1,15,None,True,54,10,1440,StepType.CLOSEST,0,1,NaN,NaN,113.0,0.0,-1.0,-1.0,8.0
1,3,0,0,1,15,None,True,54,10,1440,StepType.CLOSEST,0,2,-1.0,0.0,NaN,NaN,NaN,NaN,NaN
2,3,0,1,1,15,None,True,54,10,1440,StepType.CLOSEST,0,1,NaN,NaN,113.0,0.0,-1.0,-1.0,8.0
3,3,0,1,1,15,None,True,54,10,1440,StepType.CLOSEST,0,2,0.0,0.0,NaN,NaN,NaN,NaN,NaN
4,3,0,2,1,15,None,True,54,10,1440,StepType.CLOSEST,0,1,NaN,NaN,113.0,0.0,-1.0,-1.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5705797,749,4,1440,5,15,None,True,578,10,1440,StepType.QUEUE,0,8,504.0,908.0,NaN,NaN,NaN,NaN,NaN
5705798,749,4,1440,5,15,None,True,578,10,1440,StepType.QUEUE,0,9,466.0,950.0,NaN,NaN,NaN,NaN,NaN
5705799,749,4,1440,5,15,None,True,578,10,1440,StepType.QUEUE,0,10,547.0,862.0,NaN,NaN,NaN,NaN,NaN
5705800,749,4,1440,5,15,None,True,578,10,1440,StepType.QUEUE,0,292,NaN,NaN,64.0,1430.0,1437.0,-1.0,6.0
5705801,749,4,1440,5,15,None,True,578,10,1440,StepType.QUEUE,0,294,NaN,NaN,140.0,1440.0,-1.0,-1.0,4.0